In [3]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [4]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
scalar.ndim

0

In [6]:
#now we are creating a vector
vector = tf.constant([10,3])

vector.ndim



1

In [7]:
matrix=tf.constant([[10,5],[5,5],[6,7]])

matrix.ndim

2

In [8]:
#creating a tensor with the tf.variable and tf.constant

tf.Variable

changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

In [9]:
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [10]:
changeable_tensor[1].assign(2)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  2])>

In [11]:
#create a random tensors
random_1=tf.random.Generator.from_seed(8)
random_1= random_1.normal(shape=(3,3))

random2=tf.random.Generator.from_seed(8)
random2 = random2.normal(shape=(3,3))
random_1, random2


(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.69211644,  0.84215707, -0.06378496],
        [ 0.92800784, -0.6039789 , -0.1766927 ],
        [ 0.04221033,  0.29037967, -0.29604465]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.69211644,  0.84215707, -0.06378496],
        [ 0.92800784, -0.6039789 , -0.1766927 ],
        [ 0.04221033,  0.29037967, -0.29604465]], dtype=float32)>)

In [12]:
random_1==random2

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>

In [13]:
not_Shuffled=tf.constant([[10,7 ],[6,4],[4,5]])

#shuffle the non shuffled tensor

tf.random.shuffle(not_Shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  5],
       [ 6,  4],
       [10,  7]])>

In [14]:
tf.random.set_seed(42)
tf.random.shuffle(not_Shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 6,  4],
       [ 4,  5]])>

In [15]:
not_Shuffled 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 6,  4],
       [ 4,  5]])>

Random Seed generation

In [16]:
 tf.random.shuffle(not_Shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  5],
       [10,  7],
       [ 6,  4]])>

In [17]:
tf.random.set_seed(42)
tf.random.shuffle(not_Shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 6,  4],
       [ 4,  5]])>

In [18]:
#other ways to create tensor

tf.ones([10,7])#--> create tensor of ones

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [19]:
tf.zeros([5,5])

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [20]:
#Turn Numpy  arrays into tensors

import numpy as np

numpy_A=np.arange(1,25,dtype=np.int32)

In [21]:
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [22]:
# this is tensor
A=tf.constant(numpy_A,shape=(2,3,4))

A

# 2*3*4-->24 elements will be present in the A tensor



<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [23]:
# this is tensor
A=tf.constant(numpy_A,shape=(2,3,5))

A

# 2*3*5-->30 elements needs to be there but the number of elements is 24

TypeError: Eager execution of tf.constant with unsupported shape. Tensor [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] (converted from [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]) has 24 elements, but got `shape` (2, 3, 5) with 30 elements).

In [ ]:
B=tf.constant(numpy_A)

B

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [ ]:
A.ndim

3

In [28]:
Rank_4_matrix=tf.zeros(shape=[2,2,2,2])

Rank_4_matrix

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [29]:
tf.size(Rank_4_matrix) 



<tf.Tensor: shape=(), dtype=int32, numpy=16>

In [30]:
some_list=[1,2,3,4]
some_list[:2]

[1, 2]

In [37]:
#Tensor can be indexed 

Rank_4_matrix[:2,:1,:2,:1]





<tf.Tensor: shape=(2, 1, 2, 1), dtype=float32, numpy=
array([[[[0.],
         [0.]]],


       [[[0.],
         [0.]]]], dtype=float32)>

In [ ]:
#get the first element from each dimension from each index

Rank_4_matrix []

In [45]:
#Creating another rank of dimension which is 2


rank_2_matrix = tf.constant([[1,5],[1,6]])
rank_2_matrix



<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 5],
       [1, 6]])>

In [48]:
rank_2_matrix.shape, rank_2_matrix.ndim

(TensorShape([2, 2]), 2)

In [54]:
rank_3_matrix=rank_2_matrix[...,tf.newaxis]
rank_3_matrix

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [5]],

       [[1],
        [6]]])>

In [59]:
#Alternatively,to tf.newaxis

tf.expand_dims(rank_2_matrix,axis=-1) #-1 means expand the final axis 

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [5]],

       [[1],
        [6]]])>

In [63]:
a=tf.expand_dims(rank_2_matrix,axis=0)


In [64]:
a

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 5],
        [1, 6]]])>

Manipulatting tensors (tensor operations)


In [66]:
 #Basic operations  '+' and '-' '*' , '/' 

tensor = tf.constant([[10,5],[5,6]])
tensor +10



<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 15],
       [15, 16]])>

In [68]:
tensor = tensor+10

tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 25],
       [25, 26]])>

In [69]:
#Multiplication

tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[300, 250],
       [250, 260]])>

In [73]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 15],
       [15, 16]])>

In [74]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 25],
       [25, 26]])>

In [75]:
tf.multiply(tensor , 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[300, 250],
       [250, 260]])>

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 25],
       [25, 26]])>