In [1]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scalar.ndim

0

In [4]:
#now we are creating a vector
vector = tf.constant([10,3])

vector.ndim



1

In [5]:
matrix=tf.constant([[10,5],[5,5],[6,7]])

matrix.ndim

2

In [6]:
#creating a tensor with the tf.variable and tf.constant

tf.Variable

changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

In [7]:
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [8]:
changeable_tensor[1].assign(2)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  2])>

In [9]:
#create a random tensors
random_1=tf.random.Generator.from_seed(8)
random_1= random_1.normal(shape=(3,3))

random2=tf.random.Generator.from_seed(8)
random2 = random2.normal(shape=(3,3))
random_1, random2


(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.69211644,  0.84215707, -0.06378496],
        [ 0.92800784, -0.6039789 , -0.1766927 ],
        [ 0.04221033,  0.29037967, -0.29604465]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.69211644,  0.84215707, -0.06378496],
        [ 0.92800784, -0.6039789 , -0.1766927 ],
        [ 0.04221033,  0.29037967, -0.29604465]], dtype=float32)>)

In [10]:
random_1==random2

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>

In [11]:
not_Shuffled=tf.constant([[10,7 ],[6,4],[4,5]])

#shuffle the non shuffled tensor

tf.random.shuffle(not_Shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  5],
       [ 6,  4],
       [10,  7]])>

In [12]:
tf.random.set_seed(42)
tf.random.shuffle(not_Shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 6,  4],
       [ 4,  5]])>

In [13]:
not_Shuffled 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 6,  4],
       [ 4,  5]])>

Random Seed generation

In [14]:
 tf.random.shuffle(not_Shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  5],
       [10,  7],
       [ 6,  4]])>

In [15]:
tf.random.set_seed(42)
tf.random.shuffle(not_Shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 6,  4],
       [ 4,  5]])>

In [16]:
#other ways to create tensor

tf.ones([10,7])#--> create tensor of ones

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [17]:
tf.zeros([5,5])

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [18]:
#Turn Numpy  arrays into tensors

import numpy as np

numpy_A=np.arange(1,25,dtype=np.int32)

In [19]:
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [20]:
# this is tensor
A=tf.constant(numpy_A,shape=(2,3,4))

A

# 2*3*4-->24 elements will be present in the A tensor



<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [21]:
# this is tensor

#A=tf.constant(numpy_A,shape=(2,3,5))

#A

# 2*3*5-->30 elements needs to be there but the number of elements is 24

In [22]:
B=tf.constant(numpy_A)

B

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [23]:
A.ndim

3

In [24]:
Rank_4_matrix=tf.zeros(shape=[2,2,2,2])

Rank_4_matrix

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [25]:
tf.size(Rank_4_matrix) 



<tf.Tensor: shape=(), dtype=int32, numpy=16>

In [26]:
some_list=[1,2,3,4]
some_list[:2]

[1, 2]

In [27]:
#Tensor can be indexed 

Rank_4_matrix[:2,:1,:2,:1]





<tf.Tensor: shape=(2, 1, 2, 1), dtype=float32, numpy=
array([[[[0.],
         [0.]]],


       [[[0.],
         [0.]]]], dtype=float32)>

In [28]:
#get the first element from each dimension from each index

#Rank_4_matrix []

In [29]:
#Creating another rank of dimension which is 2


rank_2_matrix = tf.constant([[1,5],[1,6]])
rank_2_matrix



<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 5],
       [1, 6]])>

In [30]:
rank_2_matrix.shape, rank_2_matrix.ndim

(TensorShape([2, 2]), 2)

In [31]:
rank_3_matrix=rank_2_matrix[...,tf.newaxis]
rank_3_matrix

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [5]],

       [[1],
        [6]]])>

In [32]:
#Alternatively,to tf.newaxis

tf.expand_dims(rank_2_matrix,axis=-1) #-1 means expand the final axis 

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [5]],

       [[1],
        [6]]])>

In [33]:
a=tf.expand_dims(rank_2_matrix,axis=0)


In [34]:
a

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 5],
        [1, 6]]])>

Manipulatting tensors (tensor operations)


In [35]:
 #Basic operations  '+' and '-' '*' , '/' 

tensor = tf.constant([[10,5],[5,6]])
tensor +10



<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 15],
       [15, 16]])>

In [36]:
tensor = tensor+10

tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 15],
       [15, 16]])>

In [37]:
#Multiplication

tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 150],
       [150, 160]])>

In [38]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  5],
       [ 5,  6]])>

In [39]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 15],
       [15, 16]])>

In [40]:
tf.multiply(tensor , 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 150],
       [150, 160]])>

In [41]:
#Matrix multiplication in tensorflow
print(tensor)
mat=tf.constant([[12,2],[1,2]])
tf.matmul(tensor, mat)


tf.Tensor(
[[20 15]
 [15 16]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[255,  70],
       [196,  62]])>

In [42]:
print(mat.ndim , tensor.ndim )

2 2


In [43]:
tensor@ mat


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[255,  70],
       [196,  62]])>

In [44]:
mat2=tf.constant([[1,5],[2,6],[77,1]])

mat2 @ tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[  95,   95],
       [ 130,  126],
       [1555, 1171]])>

In [45]:
tensor @ tf.transpose(mat2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[  95,  130, 1555],
       [  95,  126, 1171]])>

In [46]:
mat2.dtype


tf.int32

In [47]:
mat2 = tf.cast(mat2, dtype=tf.int16)
mat2

<tf.Tensor: shape=(3, 2), dtype=int16, numpy=
array([[ 1,  5],
       [ 2,  6],
       [77,  1]], dtype=int16)>

In [48]:
#Aggregate the tensor
D =tf.constant ([-2,-1])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-2, -1])>

In [49]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 1])>

In [50]:
""" DIfferent form of aggregation 
        Get the maximum
         get the minim 
         get the mean of a tensor
         get the sum of a tensor"""

' DIfferent form of aggregation \n        Get the maximum\n         get the minim \n         get the mean of a tensor\n         get the sum of a tensor'

In [51]:
# enter the random value in the tensor

A = tf.constant(np.random.randint(0,100,size = 50))
A

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([20, 47,  9, 95, 56, 69, 14, 33, 78, 97, 93, 71, 66,  9, 69, 34, 19,
       74, 69, 17, 56,  1, 81,  9, 86, 55, 70, 12, 91, 34, 45, 96,  5, 57,
       54, 44, 72, 36, 25, 21, 48, 91, 64, 12, 16, 29, 16, 88, 17, 77])>

In [52]:
tf.size(A) , A.shape , A.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [53]:
#TO find the minimum 
tf.reduce_min(A)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [54]:
tf.reduce_min(A)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [55]:
tf.reduce_max(A)

<tf.Tensor: shape=(), dtype=int32, numpy=97>

In [56]:
tf.reduce_mean(A)

<tf.Tensor: shape=(), dtype=int32, numpy=48>

In [57]:
tf.reduce_sum(A)

<tf.Tensor: shape=(), dtype=int32, numpy=2447>

In [58]:
#to find the variance of our tensor we need to access the tensorflow probability distribution  
import tensorflow_probability as tfp

tfp.stats.variance(A)

<tf.Tensor: shape=(), dtype=int32, numpy=866>

In [59]:
# standard deviation

"""if u are getting type error in the code check out the datatype in the official documentation
"""
tf.math.reduce_std(tf.cast(A, dtype= tf.float32))
# TO FIND VARIANCE
tf.math.reduce_variance(tf.cast(A, dtype= tf.float32))



<tf.Tensor: shape=(), dtype=float32, numpy=865.9764>

Find the postional maximum and minimum


In [60]:
#Create a new tensor for finding gpositional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[20])
F

<tf.Tensor: shape=(20,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ],
      dtype=float32)>

to find the positional maximum 

In [61]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=15>

In [62]:
#index on out largest value position

F[tf.argmax(F)] 

<tf.Tensor: shape=(), dtype=float32, numpy=0.8996835>

In [63]:
#check for equality 

F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [64]:
F[tf.argmin(F)]

tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [65]:
## Squeezing the tensors ( removing all single dimensions )
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[1,1,1,1,50]))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [66]:
G.ndim

5

In [67]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [68]:
G_sequeezed = tf.squeeze(G)

G_sequeezed , G_sequeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

In [69]:
#squaring , log,square root

H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [70]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [71]:
tf.sqrt(tf.cast(H , dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [72]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# USage of Tensors and NUmpy

In [73]:
J = tf.constant(np.array([1,2,5]))
J


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 5])>

In [74]:
# convert the tensor to array
np.array(J)  ,type(np.array(J)) 

(array([1, 2, 5]), numpy.ndarray)

In [76]:
 # the default types of each are sAME
numpy_J = tf.constant(np.array([3.,5.,7.]))
tensor_J = tf.constant([6.,64.,62.]
)
numpy_J.dtype, numpy_J.dtype

(tf.float64, tf.float64)